algo = input('Digite algo: ')
print('O tipo primitivo do que você digitou é:', type(algo))
print('"{}" só contém espaços?'.format(algo), algo.isspace())
print('"{}" só contém números?'.format(algo), algo.isnumeric())
print('"{}" só contém letras?'.format(algo), algo.isalpha())
print('"{}" só contém letras e números?'.format(algo), algo.isalnum())
print('"{}" só contém maiúsculas?'.format(algo), algo.isupper())
print('"{}" só contém minúsculas?'.format(algo), algo.islower())
print('"{}" contem a primeira letra maiúscula?'.format(algo), algo.istitle())